### PR TITLE
Back end implementation for creating a shop

### LINKED ISSUE #34: Backend work for button implementation linked with issue 29
As the developer has made most progress during the sprint 4, by considering the effort, I have merged this PR and since the developed code is not working as expected as there are more changes required, this issue was created in reference with issue 29 where the developer would be continuing for the next sprint

### PR DESCRIPTION
**Pull request by ThomasMacas**
Fixes #34 

What was changed:
- Added backend implementation for shop creation button.
- Updated button front end onClick method. 

Why was it changed:
- Back-end post request was needed to create functionality for storing a shop. 
- Button onClick was updated in order to function correctly with modal. 

How was it changed:
- Created modal structure for categories that prisma uses for shop creation within useShops.jsx.
- Created createShop Function to utilize modal when create shop is clicked.  
- Updated Button on the front end to utilize createShop when onClick runs.

### CODE REVIEW

File: app/src/hooks/useShops.jsx [hunk 1]
```diff
@@ -103,6 +202,8 @@ export const useShops = () => {
     addUserToShop,
     removeUserFromShop,
     changeUserRole,
+    ModalElement,
+    createShop,
```
Comment (colinseper) [inline app/src/hooks/useShops.jsx:206]: If you'd like you can just get rid of the createShop function above and do createShop: modal here instead but that's just syntactical sugar.

File: app/src/routes/shops/index.jsx [hunk 2]
```diff
@@ -1,24 +1,38 @@
...
 import { Page, sidenavItems } from "../../components/page/page";
+import { Button } from "tabler-react-2/dist/button";
+
 const { H1 } = Typography;
 
 export const Shops = () => {
   const { user } = useAuth();
   const { shops, loading } = useShops();
+  const {
+    ModalElement,
```
Comment (colinseper) [inline app/src/routes/shops/index.jsx:17]: Maybe rename this to something like CreateShopModalElement (you will need to change line 35 to match). You can do this by doing ModalElement: CreateShopModalElement for example.

File: app/src/hooks/useShops.jsx [hunk 3]
```diff
@@ -1,5 +1,72 @@
...
+import { ShopUserPicker } from "../components/shopUserPicker/ShopUserPicker";
+import { Button } from "tabler-react-2/dist/button";
+
+const CreateShopModalContent = ({ onSubmit }) => {
+  const [name, setName] = useState("");
+  const [address, setAddress] = useState("");
+  const [phone, setPhone] = useState("");
+  const [email, setEmail] = useState("");
+  const [description, setDescription] = useState("");
+
```
Comment (colinseper) [inline app/src/hooks/useShops.jsx:14]: You may want to add an option to add an image and pass along the imageURL since it's another optional attribute like address, phone, email etc.

**Review by colinseper — CHANGES_REQUESTED** [review]
The functionality looks good! However, there's a bug currently where the color of a shop needs to be passed in to be properly displayed on the frontend. This bug is because of ShopCard.jsx specifically because the of the function
```.jsx
const COLOR_PAIRS = (color = "blue") => {
  color = color.toLowerCase();

  const pairs = {
    blue: ["rgb(1, 61, 165)", "rgb(83, 195, 238)"],
    yellow: ["rgb(204, 153, 0)", "rgb(255, 223, 79)"],
    orange: ["rgb(204, 85, 0)", "rgb(255, 179, 102)"],
    red: ["rgb(165, 0, 30)", "rgb(238, 121, 132)"],
    teal: ["rgb(0, 102, 102)", "rgb(153, 221, 221)"],
    pink: ["rgb(165, 0, 81)", "rgb(238, 141, 179)"],
    purple: ["rgb(76, 0, 153)", "rgb(186, 149, 255)"],
    green: ["rgb(0, 102, 51)", "rgb(153, 221, 153)"],
  };

  return pairs[color] || pairs.blue;
};
```

So when a null value for color is passed in via. 
```.jsx
COLOR_PAIRS(shop.color)[0]
```

on line 30, a null value is explicitly passed in so color isn't set to blue by default. Therefore I'd recommend changing the above function to have a null check at the start of the function setting color to blue if the color is passed in as null rather than the default (which will only activate when nothing is passed in - ie. color is undefined). Otherwise there will be an error when the shops try to load after they are created. 

Other than the above issue I mostly made some syntax related comments if you want to add them. Good work!

**Review by lmamillapalli786 — CHANGES_REQUESTED** [review]
Please work on the changes which I have mentioned

**Review by lmamillapalli786 — APPROVED** [review]
Thanks for the good work @ThomasMacas . Approving the changes
